name: Build & Release APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # needed to create/update a release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Install Android SDK and required components (matches compileSdk/build-tools in your app)
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 34
          build-tools: 34.0.0

      # Install Gradle (since the repo doesn't include ./gradlew)
      - name: Install Gradle 8.7 (via SDKMAN)
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradle 8.7
          echo "$HOME/.sdkman/candidates/gradle/current/bin" >> $GITHUB_PATH

      - name: Build debug APK
        run: |
          gradle --version
          gradle clean :app:assembleDebug

      - name: Upload build artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: QuadBoxHSFilm-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create/Update 'latest' GitHub Release with APK
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Latest build
          body: Auto-published debug build from CI
          draft: false
          prerelease: true
          files: app/build/outputs/apk/debug/app-debug.apk
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
